### ISSUE TITLE
Fix dev tests to not build assets in version controlled directory

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4191] opened 2023-07-17 14:58 UTC
When a developer is running the tests locally assets for the app frontend get built and put into a version controlled directory. Update the asset build process for tests to not use a version controlled directory.

## Acceptance Criteria

- [ ] No longer builds test assets into `public/images/` directory
- [ ] Builds assets and places them in a directory that is .gitignore
- [ ] Running tests against local dev environment does not place any built assets into version controlled directories

**Comment by svenaas** [comment] 2023-07-17 15:16
Well, boy, this will be nice! I'll be able to do away with
```
alias clean-images="rm -rf public/images && git checkout -- public/images"
```

**Comment by svenaas** [comment] 2023-07-31 20:14
`yarn build` (which is called by `test:prepare`) puts 95 files in `public/images` which show up with `git status` and could be accidentally committed. 

`test:client` doesn't seem to generate any assets. Neither `test:client` nor `test:server` call `test:prepare`. But `test` does, as does `test:cover`.

The 95 files are a bunch of front end assets:
- `.png   (35)`
- `.svg   (31)`
- `.eot   ( 8)`
- `.ttf   ( 8)`
- `.woff  ( 8)`
- `.woff2 ( 8)`

None of these seem to generate any **CSS** assets that show up with `git status`, however, so I wanted to double-check that detail. @apburnes, are you aware of steps to reproduce CSS generation in particular? If not I can reframe this task a little bit ("when a developer is running the tests locally assets for the app frontend get built" etc.).

**Comment by apburnes** [comment] 2023-07-31 21:51
That's what we want. Fix dev tests to not add the build assets in version controlled directory. I guess there's no css files but all the others should go somewhere outside of version control.

**Comment by svenaas** [comment] 2023-08-01 13:21
Yup, I understand that. I just wanted to be sure you weren't aware of some other situation that lead to CSS files. I'll amend the description a little.

**Comment by svenaas** [comment] 2023-08-01 13:34
I stand corrected. It creates plenty of CSS and JS files too. It's just that _those_ were already gitignored.

**Comment by svenaas** [comment] 2023-08-01 17:38
Holding off until #4208 is merged because that's going to change the Webpack configuration out from under this.

**Closed** 2023-08-08 13:45 UTC
Labels: bug, squad-pages
